### ISSUE TITLE
Module type/name

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-backend#2]
Why not using complete names/types for this module: 
- `alignak_backend_arbiter` instead of `alignakbackendarbit`
- `alignak_backend_broker` instead of `alignakbackendbrok`

It would be cleaner ...

**Comment by algorys** [comment]
I'm agree with @mohierf :+1:

**Comment by mohierf** [comment]
I propose using:
- `backend_arbiter` instead of `alignakbackendarbit`
- `backend_broker` instead of `alignakbackendbrok`
- `backend_scheduler` instead of `alignakbackendsched`

The modification for this only concerns the modules configuration files :wink:

**Comment by mohierf** [comment]
@algorys : perharps an impact in the Alignak installation tutorial?

**Comment by algorys** [comment]
@mohierf Yes I'll update this section.
